<?php

/**
 * @file
 * Provides currency information and allows users to add custom currencies.
 */

/**
 * Indicates a currency's sign/code should be displayed before the amount.
 */
define('CURRENCY_INDICATOR_BEFORE', 1);

/**
 * Indicates a currency's sign/code should be displayed after the amount.
 */
define('CURRENCY_INDICATOR_AFTER', 2);

/**
 * Implements hook_hook_info().
 */
function currency_hook_info() {
  $hooks['currency_info'] = array(
    'group' => 'currency',
  );
  $hooks['currency_info_alter'] = array(
    'group' => 'currency',
  );

  return $hooks;
}

/**
 * Implements hook_views_api().
 */
function currency_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'currency') . '/views',
  );
}
