<?php

/**
 * @file
 * Provides currency information and allows users to add custom currencies.
 */

require_once __DIR__ . '/vendor/autoload.php';

/**
 * The default locale.
 */
define('CURRENCY_DEFAULT_LOCALE', 'en_US');

/**
 * Implements hook_hook_info().
 */
function currency_hook_info() {
  $hooks['currency_info'] = array(
    'group' => 'currency',
  );
  $hooks['currency_info_alter'] = array(
    'group' => 'currency',
  );
  $hooks['locale_pattern_info'] = array(
    'group' => 'currency',
  );
  $hooks['locale_pattern_info_alter'] = array(
    'group' => 'currency',
  );

  return $hooks;
}

/**
 * Implements hook_views_api().
 */
function currency_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'currency') . '/views',
  );
}

/**
 * Implements Ctools exportables save callback.
 */
function currency_ctools_export_object_save(CurrencyExportableInterface $exportable) {
  $exportable->validate();
  $exportable->export_type = $exportable->export_type | EXPORT_IN_DATABASE;
  $schema = drupal_get_schema($exportable->table);
    $fields = array();
  foreach ($schema['fields'] as $field => $info) {
    if (property_exists($exportable, $field)) {
      $fields[$field] = $exportable->$field;
    }
  }
  $primary_key = $schema['primary key'][0];

  return db_merge($exportable->table)
    ->key(array(
      $primary_key => $exportable->$primary_key,
    ))
    ->fields($fields)
    ->execute();
}
