<?php

/**
 * @file
 * Contains hook implementations.
 */

/**
 * Implements hook_menu_link_defaults().
 */
function currency_menu_link_defaults() {
  return \Drupal::service('currency.hook.menu_link_defaults')->invoke();
}

/**
 * Implements hook_element_info().
 */
function currency_element_info() {
  return \Drupal::service('currency.hook.element_info')->invoke();
}

/**
 * Implements hook_permission().
 */
function currency_permission() {
  return \Drupal::service('currency.hook.permission')->invoke();
}
